spring:
  main:
    banner-mode: "off"
  application:
    name: voisin-online
  data:
    mongodb:
      host: localhost
      port: 27017
      database: voisin_online
      username: root
      password: root
      authentication-database: admin
server:
  port: 8081

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data.mongodb.core.MongoTemplate: INFO
    org.apache.http: INFO
    org.springframework.web: INFO